# Generated by Django 2.2.5 on 2019-09-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Слово')),
                ('translation', models.CharField(max_length=64, verbose_name='Перевод')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='learned_words',
            field=models.ManyToManyField(related_name='learned_users', to='english.Word'),
        ),
        migrations.AddField(
            model_name='user',
            name='learning_words',
            field=models.ManyToManyField(related_name='learning_users', to='english.Word'),
        ),
    ]
