# Generated by Django 2.2.5 on 2019-09-21 18:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_auto_20190921_1420'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cookie',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
